// src/App.tsx
/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { useEffect } from 'react';
import { useStore } from './store';
import { BottomNav } from './components/BottomNav';
import { Kader } from './components/Kader';
import { Aufstellung } from './components/Aufstellung';
import { Daten } from './components/Daten';
import { Toaster } from './components/ui/sonner';

export default function App() {
  const { activeTab, tick } = useStore();

  useEffect(() => {
    const interval = setInterval(() => {
      tick();
    }, 1000);
    return () => clearInterval(interval);
  }, [tick]);

  const renderTab = () => {
    switch (activeTab) {
      case 'KADER': return <Kader />;
      case 'AUFSTELLUNG':
      case 'MATCH': return <Aufstellung />;
      case 'DATEN': return <Daten />;
      default: return null;
    }
  };

  return (
    <div className="flex flex-col h-[100dvh] w-full bg-white text-[#161616] overflow-hidden font-sans select-none antialiased">
      <main className="flex-1 relative overflow-hidden">
        {renderTab()}
      </main>
      
      <Toaster />
      <BottomNav />
    </div>
  );
}

// src/App.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { store } from './store.svelte';
  import Kader from './components/Kader.svelte';
  import Aufstellung from './components/Aufstellung.svelte';
  import Daten from './components/Daten.svelte';
  import BottomNav from './components/BottomNav.svelte';

  let timer: any;

  onMount(() => {
    timer = setInterval(() => {
      store.tick();
    }, 1000);
  });

  onDestroy(() => {
    if (timer) clearInterval(timer);
  });
</script>

<div class="h-full flex flex-col bg-white overflow-hidden select-none">
  <main class="flex-1 overflow-hidden relative">
    {#if store.activeTab === 'KADER'}
      <Kader />
    {:else if store.activeTab === 'AUFSTELLUNG' || store.activeTab === 'MATCH'}
      <Aufstellung />
    {:else if store.activeTab === 'DATEN'}
      <Daten />
    {/if}
  </main>
  
  <BottomNav />
</div>
